-- MySQL Script generated by MySQL Workbench
-- Fri Apr 24 10:39:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ATO_authenticator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ATO_authenticator` ;

-- -----------------------------------------------------
-- Schema ATO_authenticator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ATO_authenticator` DEFAULT CHARACTER SET utf8 ;
USE `ATO_authenticator` ;

-- -----------------------------------------------------
-- Table `ATO_authenticator`.`priviliges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`priviliges` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`priviliges` (
  `PRIVid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `desc` TEXT NULL,
  `notes` TEXT NULL,
  `dailyHash` VARCHAR(80) NULL DEFAULT '007',
  PRIMARY KEY (`PRIVid`),
  UNIQUE INDEX `PRIVid_UNIQUE` (`PRIVid` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATO_authenticator`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`persons` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`persons` (
  `LOGid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AGSno` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `desc` TEXT NULL,
  `notes` TEXT NULL,
  PRIMARY KEY (`LOGid`),
  UNIQUE INDEX `LOGid_UNIQUE` (`LOGid` ASC),
  UNIQUE INDEX `AGSno_UNIQUE` (`AGSno` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATO_authenticator`.`passwords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`passwords` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`passwords` (
  `PASSid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LOGid` INT UNSIGNED NOT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `password` VARCHAR(45) NOT NULL,
  `current` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`PASSid`),
  INDEX `LOGID_idx` (`LOGid` ASC),
  UNIQUE INDEX `PASSid_UNIQUE` (`PASSid` ASC),
  CONSTRAINT `LOGid_pass`
    FOREIGN KEY (`LOGid`)
    REFERENCES `ATO_authenticator`.`persons` (`LOGid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATO_authenticator`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`applications` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`applications` (
  `APPid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `appName` VARCHAR(45) NOT NULL,
  `desc` TEXT NULL,
  `notes` TEXT NULL,
  PRIMARY KEY (`APPid`),
  UNIQUE INDEX `APPid_UNIQUE` (`APPid` ASC),
  UNIQUE INDEX `appName_UNIQUE` (`appName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATO_authenticator`.`persons_priviliges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`persons_priviliges` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`persons_priviliges` (
  `PPRid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRIVid` INT UNSIGNED NOT NULL,
  `LOGid` INT UNSIGNED NOT NULL,
  `LOGidAssigned` INT UNSIGNED NOT NULL DEFAULT 0,
  `timestampApplied` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `timestampAssigned` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `timestampStart` DATETIME NULL,
  `timestampEnd` DATETIME NULL,
  PRIMARY KEY (`PPRid`),
  UNIQUE INDEX `PPRid_UNIQUE` (`PPRid` ASC),
  INDEX `LOGidAssigner_idx` (`LOGidAssigned` ASC),
  INDEX `LOGid_idx` (`LOGid` ASC),
  INDEX `PRIVid_idx` (`PRIVid` ASC),
  CONSTRAINT `PRIVid_PersPrivs`
    FOREIGN KEY (`PRIVid`)
    REFERENCES `ATO_authenticator`.`priviliges` (`PRIVid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LOGid_PersPrivs`
    FOREIGN KEY (`LOGid`)
    REFERENCES `ATO_authenticator`.`persons` (`LOGid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LOGidAssigner_PersPrivs`
    FOREIGN KEY (`LOGidAssigned`)
    REFERENCES `ATO_authenticator`.`persons` (`LOGid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATO_authenticator`.`application_priviliges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`application_priviliges` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`application_priviliges` (
  `APRid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `APPid` INT UNSIGNED NOT NULL,
  `PRIVid` INT UNSIGNED NOT NULL,
  `desc` TEXT NULL,
  `notes` TEXT NULL,
  `timestampApplied` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `timestampStart` DATETIME NULL,
  `timestampEnd` DATETIME NULL,
  PRIMARY KEY (`APRid`),
  INDEX `APPID_idx` (`APPid` ASC),
  INDEX `PRIVID_idx` (`PRIVid` ASC),
  UNIQUE INDEX `APRid_UNIQUE` (`APRid` ASC),
  CONSTRAINT `APPid_AppPrivs`
    FOREIGN KEY (`APPid`)
    REFERENCES `ATO_authenticator`.`applications` (`APPid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PRIVid_AppPrivs`
    FOREIGN KEY (`PRIVid`)
    REFERENCES `ATO_authenticator`.`priviliges` (`PRIVid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATO_authenticator`.`hashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATO_authenticator`.`hashes` ;

CREATE TABLE IF NOT EXISTS `ATO_authenticator`.`hashes` (
  `LOGid` INT UNSIGNED NOT NULL,
  `Hash` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `LOGid_hash_idx` (`LOGid` ASC),
  CONSTRAINT `LOGid_hash`
    FOREIGN KEY (`LOGid`)
    REFERENCES `ATO_authenticator`.`persons` (`LOGid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS user_client;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user_client' IDENTIFIED BY '45h2g45hg23kjh53j456276DFSJG';

GRANT SELECT, INSERT, TRIGGER ON TABLE `ATO_authenticator`.* TO 'user_client';
GRANT SELECT ON TABLE `ATO_authenticator`.* TO 'user_client';
SET SQL_MODE = '';
DROP USER IF EXISTS user_admin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user_admin' IDENTIFIED BY 'gkh5g63khgSDFRHGjjkl23452';

GRANT ALL ON `ATO_authenticator`.* TO 'user_admin';
GRANT SELECT ON TABLE `ATO_authenticator`.* TO 'user_admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `ATO_authenticator`.* TO 'user_admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `ATO_authenticator`.* TO 'user_admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ATO_authenticator`.`priviliges`
-- -----------------------------------------------------
START TRANSACTION;
USE `ATO_authenticator`;
INSERT INTO `ATO_authenticator`.`priviliges` (`PRIVid`, `name`, `desc`, `notes`, `dailyHash`) VALUES (DEFAULT, 'Order of Queensland', 'Recipients earn the right to play minesweeper, and drive really badly', 'god damn these people drive poorly', NULL);
INSERT INTO `ATO_authenticator`.`priviliges` (`PRIVid`, `name`, `desc`, `notes`, `dailyHash`) VALUES (DEFAULT, 'Procrastinator', 'Hard earned gaming time', 'too much gaming time', NULL);
INSERT INTO `ATO_authenticator`.`priviliges` (`PRIVid`, `name`, `desc`, `notes`, `dailyHash`) VALUES (DEFAULT, 'Minesweeper', 'Yes', 'Hahaha', NULL);
INSERT INTO `ATO_authenticator`.`priviliges` (`PRIVid`, `name`, `desc`, `notes`, `dailyHash`) VALUES (DEFAULT, 'Discord', 'Hmmm', 'Yote', NULL);
INSERT INTO `ATO_authenticator`.`priviliges` (`PRIVid`, `name`, `desc`, `notes`, `dailyHash`) VALUES (DEFAULT, 'Portal 2', 'Another generic priv', 'Yes indeed', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ATO_authenticator`.`persons`
-- -----------------------------------------------------
START TRANSACTION;
USE `ATO_authenticator`;
INSERT INTO `ATO_authenticator`.`persons` (`LOGid`, `AGSno`, `login`, `firstName`, `lastName`, `phone`, `email`, `desc`, `notes`) VALUES (DEFAULT, '1234Banana', 'BananaKing', 'Humphrey', 'Appleby', '12345677890', 'Yes@Yes.Yes', 'Has a knighthood', 'Absolute Champion Bloke - ACB');
INSERT INTO `ATO_authenticator`.`persons` (`LOGid`, `AGSno`, `login`, `firstName`, `lastName`, `phone`, `email`, `desc`, `notes`) VALUES (DEFAULT, '5678Orange', 'CombOvers22', 'Monald', 'Bump', '0987654321', 'Nope@Nope.Nope', 'spray painted orange', 'lots of complaints');
INSERT INTO `ATO_authenticator`.`persons` (`LOGid`, `AGSno`, `login`, `firstName`, `lastName`, `phone`, `email`, `desc`, `notes`) VALUES (DEFAULT, 'AOA43', 'AussieOutbackAdventures', 'Yes', 'Yep', '90789092385', 'HAHA@HAHA.HAHA', 'Yes', 'Yes indeed');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ATO_authenticator`.`applications`
-- -----------------------------------------------------
START TRANSACTION;
USE `ATO_authenticator`;
INSERT INTO `ATO_authenticator`.`applications` (`APPid`, `appName`, `desc`, `notes`) VALUES (DEFAULT, 'Minesweeper', 'Fun', 'I played this too much as a member of the low socio-economic population in childhood');
INSERT INTO `ATO_authenticator`.`applications` (`APPid`, `appName`, `desc`, `notes`) VALUES (DEFAULT, 'Discord', 'High restrictions needed here', 'Probably a security risk');
INSERT INTO `ATO_authenticator`.`applications` (`APPid`, `appName`, `desc`, `notes`) VALUES (DEFAULT, 'Portal 2', 'There is no cake', 'There is merely the illusion of cake');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ATO_authenticator`.`application_priviliges`
-- -----------------------------------------------------
START TRANSACTION;
USE `ATO_authenticator`;
INSERT INTO `ATO_authenticator`.`application_priviliges` (`APRid`, `APPid`, `PRIVid`, `desc`, `notes`, `timestampApplied`, `timestampStart`, `timestampEnd`) VALUES (DEFAULT, 1, 3, 'dfgjdfgj', 'dfghjdfgj', DEFAULT, NULL, NULL);
INSERT INTO `ATO_authenticator`.`application_priviliges` (`APRid`, `APPid`, `PRIVid`, `desc`, `notes`, `timestampApplied`, `timestampStart`, `timestampEnd`) VALUES (DEFAULT, 2, 4, 'hrfghf', 'dfgjdg', DEFAULT, NULL, NULL);
INSERT INTO `ATO_authenticator`.`application_priviliges` (`APRid`, `APPid`, `PRIVid`, `desc`, `notes`, `timestampApplied`, `timestampStart`, `timestampEnd`) VALUES (DEFAULT, 3, 5, 'fgjhdfg', 'dfgjdf', DEFAULT, NULL, NULL);

COMMIT;

